name: CI
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # the following make command installs a script under .git, which makes git
      # complain about detecting dubious ownership in repository
      - name: work around weird permissions problem
        run: git config --global --add safe.directory '*'

      - name: Compile LaTeX document
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            resume.log
            resume.out
            resume.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      # - name: Upload resume.log
